[package]
name = "paperback"
version = "0.8.0"
description = "An accessible, light-weight, fast ebook and document reader"
license = "MIT"
repository = "https://github.com/trypsynth/paperback"
edition = "2024"
rust-version = "1.87.0"

[workspace]
members = ["xtask"]

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
bitflags = "2.10.0"
ego-tree = "0.10.0"
encoding_rs = "0.8.35"
hayro-interpret = "0.5.0"
hayro-syntax = "0.5.0"
kurbo = "0.12.0"
libchm = "0.1.0"
percent-encoding = "2.3.2"
pulldown-cmark = { version = "0.13.0", default-features = false, features = ["html"] }
regex = "1.12.2"
roman = "0.1"
roxmltree = "0.21.1"
scraper = "0.25.0"
serde = { version = "1.0.228", default-features = false, features = ["derive", "std"] }
sha1 = "0.10.6"
ureq = { version = "3.1.4", default-features = false, features = ["json", "rustls"] }
windows = { version = "0.62.2", features = ["Win32_UI_Accessibility", "Win32_System_Com", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Ole", "Win32_System_Variant"] }
wxdragon = { git = "https://github.com/AllenDang/wxDragon", branch = "main", version = "0.9.8", features = ["webview"] }
wxdragon-sys = { git = "https://github.com/AllenDang/wxDragon", branch = "main", version = "0.9.8" }
zip = { version = "7.2.0", default-features = false, features = ["deflate"] }

[build-dependencies]
embed-manifest = "1.5.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
