[package]
name = "paperback"
version = "0.8.0"
description = "An accessible, light-weight, fast ebook and document reader"
license = "MIT"
repository = "https://github.com/trypsynth/paperback"
edition = "2024"
rust-version = "1.87.0"

[workspace]
members = ["xtask"]

[dependencies]
anyhow = "1.0.101"
base64 = "0.22.1"
bitflags = "2.10.0"
ego-tree = "0.10.0"
encoding_rs = "0.8.35"
hayro-interpret = "0.5.0"
hayro-syntax = "0.5.0"
kurbo = "0.12.0"
libchm = "0.1.0"
live-region = "0.1.3"
percent-encoding = "2.3.2"
pulldown-cmark = { version = "0.13.0", default-features = false, features = ["html"] }
regex = "1.12.3"
roman = "0.1"
roxmltree = "0.21.1"
rtf-parser = "0.4.2"
scraper = "0.25.0"
serde = { version = "1.0.228", default-features = false, features = ["derive", "std"] }
sha1 = "0.10.6"
ureq = { version = "3.2.0", default-features = false, features = ["json", "rustls"] }
wxdragon = { version = "0.9.9", features = ["webview"] }
wxdragon-sys = "0.9.9"
zip = { version = "7.3.0", default-features = false, features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_UI_Accessibility", "Win32_System_Com", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Ole", "Win32_System_Variant"] }

[build-dependencies]
embed-manifest = "1.5.0"
winres = "0.1.12"

[dev-dependencies]
rstest = "0.26.1"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
