[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.1.9", default-features = false }
tar = "0.4.44"
zip = { version = "7.4.0", default-features = false, features = ["deflate"] }
walkdir = "2.5.0"
